### ISSUE TITLE
Using concise-utils only

### ISSUE THREAD

**Issue by yshterev** [ConciseCSS/concise-utils#38]
I am trying to use concise-utils only. 

The docs say install with `npm install concise-utils` and then `@import 'node_modules/concise-utils/concise-utils'` in scss, but `concise-utils` needs `@import "node_modules/concise.css/globals";`

There is another file in the npm of `concise-utils` called `dist.scss`. It loads `concise.css/globals` and gets processed by sass without problems.

The problem is.. when I use `_mtl`, for example I see in the browser `margin-top: 3lh;` instead of valid margin value. 

What am I doing wrong?

**Comment by ghost** [comment]
Hi @yshterev

If you want to use the sources of Concise Utils you will need to import the globals file too, this can be done by importing `dist.scss` (which already includes global.scss) or importing `globals.scss` by yourself separated. Then you have to use the Concise CLI instead of Sass directly to get the CSS since Concise uses some features that are not available in Sass alone, like the `lh` unit. The advantage of using the source is that the styles will adapt to your settings.

Alternatively, you can import the compiled CSS file from the `dist` directory, but it will use the default settings.

Let me know if that's clear!

**Comment by ghost** [comment]
By the way, just as a note: this behavior will change in the next major version, although that will take some time.

**Comment by yshterev** [comment]
Yes! I understand that. Even when I load `dist.scss` i still get `lh` units instead of `rem`. When I load processed CSS directly It works.

Thanks for the quick response.

**Comment by ghost** [comment]
Are you using the Concise CLI to compile?

**Comment by yshterev** [comment]
I am not using Concise CLI. I am just importing `dist.scss` from node_modules in the scss file of my project, and building everything with `gulp-sass`. 

In the docs it says concise cli outputs `css` file. Is one supposed to use the `css` output file from the concise cli only?

**Comment by ghost** [comment]
Yeah, so the thing is that Concise includes some features that are not available by Sass. The Concise CLI just wraps everything you need, which is the Sass compiler and some PostCSS plugins. If using the CLI isn't for you, you will need to manually include those PostCSS plugins in your build system, especially [PostCSS-LH](https://github.com/jameskolce/postcss-lh) which is the thing that transforms the `lh` units that you are seeing in your CSS.

Here is the list of plugins:

[postcss-input-range](https://github.com/jonathantneal/postcss-input-range)
[postcss-lh](https://github.com/jameskolce/postcss-lh)
[postcss-custom-media](https://github.com/postcss/postcss-custom-media)
[postcss-media-minmax](https://github.com/postcss/postcss-media-minmax)

Let me know if that solves your problem!

**Comment by yshterev** [comment]
Yes. I guess that's what I have missed. Thanks!

**Comment by ghost** [comment]
Alright!
